kind: pipeline
name: default

.environment-variables: &environment-variables
  AWS_ACCESS_KEY_ID:
    from_secret: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    from_secret: AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: eu-west-1

steps:

- name: s3-publish
  image: mesosphere/aws-cli:latest
  environment:
    <<: *environment-variables
  commands:
    - s3 cp ./ s3://allthe.football/ --recursive --exclude "./infrastructure" --exclude "./LICENSE" --exclude ".gitignore" --exclude ".drone.yml"
  # when:
  #   branch:
  #     include:
  #       - master
  #   event:
  #     - push
